language: go
go:
  - 1.7
  - 1.8
  - tip
before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/hashicorp/go-multierror
script:
  - go vet .
  - golint .
  - go test -race -v .
